app = "prednjica"
primary_region = "cdg"

[build]
  # image = "ghcr.io/tminaorg/prednjica:latest"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 20
    soft_limit = 10
  
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
