app = "frontend"
primary_region = "cdg"

[build]
  image = "ghcr.io/hearchco/frontend:latest"

[env]
  ORIGIN = "https://hearch.co"
  PUBLIC_API_URL_SSR = "http://hearchco.flycast"
  PUBLIC_API_URL_CSR = "https://api.hearch.co"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 20
    soft_limit = 10

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
