name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PUBLIC_UI_VERSION: ${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm' # must be preinstalled

      # switch svelte.config.js to use aws adapter
      - run: make adapter-aws

      # install dependencies and build
      - run: make install
      - run: make compile

      # zip the build directory
      - run: |
          cd build/cloudfront && cp index.js hearchco_cf_index_aws.js . && cd ../..
          cd build/lambda && zip -r hearchco_index_mjs_aws.zip . && cd ../..
          cd build/s3 && zip -r hearchco_s3_assets_aws.zip . && cd ../..

      # upload the build to the release
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            build/cloudfront/hearchco_cf_index_aws.js
            build/lambda/hearchco_index_mjs_aws.zip
            build/s3/hearchco_s3_assets_aws.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
