name: Testing CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PUBLIC_UI_VERSION: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm' # must be preinstalled

      - run: make install
      - run: make compile
      - run: make check
      - run: make lint
      - run: make test
